# Generated by Django 3.2.7 on 2023-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
